### ISSUE TITLE
Support for yaml, .properties files?

### ISSUE THREAD

**Issue by psrin7** [miniclip/gonsul#1] opened 2018-06-27 15:27 UTC
Hi,
Just wondering if support for yaml and .properties files (with option to expand) be included in the future release ?

**Comment by eduardev** [comment] 2018-06-28 22:01
Hi @psrin7

I am going to do some clean up work this weekend and create a release for download, I can add that up into the first official release then.

**Comment by psrin7** [comment] 2018-06-28 23:35
Great, thanks..

**Comment by eduardev** [comment] 2018-07-01 09:19
Hi, part of the issue has been addressed (now you can pass as parameter what file extensions to accept). Although option to expand has not done yet unfortunately, because that will take a bit more thinking and work, specially `.properties` file as it's a not a common format (outside Java world) and parsing it will take a bit more work.

I'll look into it asap ;)

**Comment by psrin7** [comment] 2018-07-01 14:46
Thanks Eduardo. We have many microservices written in Vertx and hence the
request.

**Comment by eduardev** [comment] 2019-10-28 21:43
fixed in #10

**Comment by Garagoth** [comment] 2020-02-10 16:11
Um, any chance for implementing yaml file support? Or is this kind of stalled?

**Comment by eduardev** [comment] 2020-02-10 16:32
Hi @Garagoth 

Not stalled, project has been stable and regarding this feature we decided to not go forward with it mainly because of properties file. On the other hand YAML would be perfectly doable.

But just to make it clear, we're talking about the expanding the file contents right? Because as a file extensions, we can pass any file extension and use it's contents as Consul value.

**Comment by Garagoth** [comment] 2020-02-10 18:40
Yes, expanding contents of yaml files.

**Comment by eduardev** [comment] 2020-03-25 00:33
Hi @Garagoth 

Sorry for the delay on this.
Just did a quick try on YAML validation and expanding. Could you do a quick try https://github.com/miniclip/gonsul/tree/feature/1_support_yaml ?

If not I'll try to give it a spin tomorrow, and if all good all merge it to master. I would like it to run for a while in a few scenarios before actually making a release though, but I don't have use cases for yaml files where I can leave Gonsul running.

**Comment by Garagoth** [comment] 2020-04-02 09:56
```
profiles:
  - test
  - central_logging
```
results in:
```
key: profiles
value: [euro-test central_logging]
```

Also, all values in yaml must be in "" to work.

**Comment by eduardev** [comment] 2020-04-02 12:39
I don't understand.

YAML lists are equivalent to arrays and treated as arrays, meaning we have no keys to expand on. It's working as designed and it also happens with JSON arrays `[]`

Also, what do you mean with `all values in yaml must be in "" to work` ?

**Comment by Garagoth** [comment] 2020-04-03 10:38
yaml list (or array) is stored into Consul key as one string value, with separator set to space so it is not even a valid json array. And it is not quoted as well...

As for values in "":
expansion worked only if all yaml values were quoted.
If values were not quoted in yaml file, it was simply not expanded and stored as a single value with whole yaml file contents.

**Comment by nvx** [comment] 2020-11-23 01:54
https://yaml-online-parser.appspot.com/ is a handy tool that can parse ymal and convert to json so you can see how it parses.

```
key: profiles
value: [euro-test central_logging]
```

is equivalent to 

```
{
  "key": "profiles", 
  "value": [
    "euro-test central_logging"
  ]
}
```

Which I think is the issue.

I'm personally interested in the validation of yaml files aspect only rather than expanding, so am keen to see a release version with these changes included.

**Comment by paulo-ferraz-oliveira** [comment] 2020-11-23 18:42
Hi, @nvx. Thank you for your feedback. Let me discuss some stuff internally so either me or somebody else can get back to this.

**Comment by eduardev** [comment] 2020-11-24 23:55
Guys, apologies, but I'm not following.
So if we have the following yaml file /repo/config.yaml:
```
single_key: "single value"
list_key:
  - test_1
  - test_2
```

This is equivalent to the json file /repo/config.json:
```
{
  "single_key": "single value",
  "list_key": [
    "test_1",
    "test_2"
  ]
}
```

This will in turn be (in both cases) published to consul as:
`repo/config/single_key` -> `single value`
`repo/config/list_key` -> `[test_1 test_2]`

**Notes**:
1. The above behaviour is what's in the latest Gonsul version.
2. @nvx Gonsul is validating yaml with most used lib available (https://github.com/go-yaml/yaml)
3. The only issue I can see, is that in the documentation it says that we should add to consul a bracketed comma separated values for the array, and we are not indeed adding any comas (instead a bracketed _space_ separated values)
4. There is "easy" way of representing a slice/array inside Consul. Consul only supports strings. Slices/Arrays are not maps.

Again, apologies if I'm missing something here, and please help me understand better what behaviour would you expect from Gonsul dealing with slices/arrays.

**Comment by paulo-ferraz-oliveira** [comment] 2020-11-25 00:42
> Last release was for YAML support, the only reason this ticket was left open is because of .properties files, which is a whole another level of complexity where I didn't have time for.

👍, we've not heard from @psrin7 for more than 2 years, so either the problem is no longer a problem, or an alternative was found. We're closing this for now. Feel free to open a new issue or pull request to handle a specific use case.

**Closed by paulo-ferraz-oliveira** 2020-11-25 00:42 UTC
Labels: enhancement

**Comment by nvx** [comment] 2020-11-25 00:47
https://github.com/miniclip/gonsul/releases doesn't seem to have binaries for anything newer than v0.2.1 which doesn't have yaml support from what I can tell?

Install instructions in the readme says to use the releases page.

**Comment by paulo-ferraz-oliveira** [comment] 2020-11-25 00:53
Oh, I see. Could you open a new issue with your specific request so we can track it? Thanks.
